apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/gotk-components.yaml
  - flux-system/gotk-sync.yaml
  - apps/vs-book-app.yaml
  - apps/gmail-frontend.yaml
  - apps/synth.yaml
  - cloudflared
